services:
  - type: web
    name: velonix-obfuscator-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromEnv: DISCORD_BOT_TOKEN

  - type: worker
    name: velonix-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromEnv: DISCORD_BOT_TOKEN